---
apiVersion: v1
kind: Secret
metadata:
  name: aac-token-secret
  namespace: aap
  annotations:
    kubernetes.io/service-account.name: aac-service-account
type: kubernetes.io/service-account-token
