---
apiVersion: v1
kind: Secret
metadata:
  name: eda-token-secret
  namespace: aap
  annotations:
    kubernetes.io/service-account.name: "eda-service-account"
type: kubernetes.io/service-account-token
