---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-26/de-supported-rhel9:1.2.2-5

dependencies:
  galaxy:
    collections:
      - name: ansible.eda
      - name: community.general
      
      # --- ADD THE JUNIPER GIT URL HERE ---
      - name: https://github.com/Juniper/k8s.eda.git
        type: git

  python:
    - aiokafka
    - aiohttp
    - watchdog
    # --- CRITICAL DEPENDENCY FOR THE JUNIPER EXTENSION ---
    - kubernetes_asyncio

  system:
    - git
    - unzip

options:
  package_manager_path: /usr/bin/microdnf
