---
- name: Listen for OpenShift events
  hosts: all
  sources:
    - name: Listen for OpenShift events
      juniper.eda.k8s:
        kubeconfig: "{{ eda.filename.kubeconfig }}"
        kinds:
          - api_version: v1
            kind: Namespace
  rules:
    - name: Set Resource Quotas to a Namespace
      condition: event.resource.kind == "Namespace" and (event.type == "ADDED" or event.type == "MODIFIED")
      action:
        run_job_template:
          name: OpenShift Set Resource Quota on Namespace
          organization: Default
          job_args:
            extra_vars:
              namespace: "{{ event.resource.metadata.name }}"
